version: '3.9'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: recipe
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  recipe-app:
    depends_on:
      - mongodb
    build:
      context: ./
      dockerfile: docker/Dockerfile
    # restart: unless-stopped
    ports:
      - "8081:8081"
    links:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: docker


volumes:
  mongodb_data_container: